class CreateSamples < ActiveRecord::Migration
  def change
    create_table :samples do |t|
      t.string :bcr_patient_uuid
      t.string :file_name
      t.string :folder_name_from_manifest
      t.string :bcr_patient_barcode
      t.date :form_completion_date
      t.string :histologic_diagnosis
      t.string :prospective_collection
      t.string :retrospective_collection
      t.string :gender
      t.string :birth_days_to
      t.string :race
      t.string :ethnicity
      t.string :history_other_malignancy
      t.string :history_neoadjuvant_treatment
      t.string :initial_pathologic_dx_year
      t.string :ajcc_staging_edition
      t.string :ajcc_tumor_pathologic_pt
      t.string :ajcc_nodes_pathologic_pn
      t.string :ajcc_metastasis_pathologic_pm
      t.string :ajcc_pathologic_tumor_stage
      t.string :residual_tumor
      t.string :lymph_nodes_examined
      t.string :lymph_nodes_examined_count
      t.integer :lymph_nodes_examined_he_count
      t.integer :lymph_nodes_examined_ihc_count
      t.string :vital_status
      t.integer :last_contact_days_to
      t.integer :death_days_to
      t.string :tumor_status
      t.integer :cea_level_pretreatment
      t.string :specimen_non_node_tumor_deposits
      t.integer :circumferential_resection_margin_crm
      t.string :vascular_invasion_indicator
      t.string :lymphovascular_invasion_indicator
      t.string :perineural_invasion
      t.string :microsatellite_instability
      t.string :loci_tested_count
      t.string :loci_abnormal_count
      t.string :mismatch_rep_proteins_tested_by_ihc
      t.string :mismatch_rep_proteins_loss_ihc
      t.string :kras_gene_analysis_indicator
      t.string :kras_mutation_found
      t.string :kras_mutation_codon
      t.string :braf_gene_analysis_indicator
      t.string :braf_gene_analysis_result
      t.string :history_other_malignancy
      t.string :history_colon_polyps
      t.string :colon_polyps_at_procurement_indicator
      t.integer :weight_kg_at_diagnosis
      t.integer :height_cm_at_diagnosis
      t.integer :family_history_colorectal_cancer
      t.string :radiation_treatment_adjuvant
      t.string :pharmaceutical_tx_adjuvant
      t.string :treatment_outcome_first_course
      t.string :new_tumor_event_dx_indicator
      t.integer :age_at_initial_pathologic_diagnosis
      t.string :anatomic_neoplasm_subdivision
      t.string :clinical_M
      t.string :clinical_N
      t.string :clinical_T
      t.string :clinical_stage
      t.string :days_to_initial_pathologic_diagnosis
      t.string :days_to_patient_progression_free
      t.string :days_to_tumor_progression
      t.string :disease_code
      t.string :eastern_cancer_oncology_group
      t.string :extranodal_involvement
      t.string :icd_10
      t.string :icd_o_3_histology
      t.string :icd_o_3_site
      t.string :informed_consent_verified
      t.string :initial_pathologic_diagnosis_method
      t.string :karnofsky_performance_score
      t.string :number_pack_years_smoked
      t.string :patient_id
      t.string :project_code
      t.string :stage_other
      t.string :stopped_smoking_year
      t.string :tissue_source_site
      t.string :tobacco_smoking_history
      t.string :tumor_tissue_site
      t.string :year_of_tobacco_smoking_onset

      t.timestamps null: false
    end
  end
end
